/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GeneratorDLG.h"
#include "dac_wave.h"
#include "string.h"
#include "stdio.h"
#include "MainDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x06)
#define ID_GRAPH_0     (GUI_ID_USER + 0x07)
#define ID_BUTTON_0     (GUI_ID_USER + 0x08)
#define ID_BUTTON_1     (GUI_ID_USER + 0x09)
#define ID_BUTTON_2     (GUI_ID_USER + 0x0A)
#define ID_BUTTON_3     (GUI_ID_USER + 0x0B)
#define ID_BUTTON_4     (GUI_ID_USER + 0x0C)
#define ID_BUTTON_5     (GUI_ID_USER + 0x0D)
#define ID_BUTTON_6     (GUI_ID_USER + 0x0E)
#define ID_TEXT_0     (GUI_ID_USER + 0x0F)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

extern u16 *Array_Wavedata;  //全局变量，指向波形数组
extern u32 Fre_Wave;          //输出波形频率
GRAPH_DATA_Handle  hData_2;
WM_HTIMER hTimer_3;
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Generator", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 19, 29, 400, 280, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Fre+", ID_BUTTON_0, 55, 341, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Fre-", ID_BUTTON_1, 55, 394, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Sine", ID_BUTTON_2, 510, 50, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Sawtooth", ID_BUTTON_3, 510, 120, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Square", ID_BUTTON_4, 510, 190, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Triangular", ID_BUTTON_5, 510, 260, 80, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_6, 728, 0, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Fre:", ID_TEXT_0, 177, 376, 100, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	int     i;
	char Disp_2[20];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_PAINT:
			GUI_SetBkColor(GUI_WHITE);  //设置背景色
			GUI_Clear();
			break;
	case WM_INIT_DIALOG:
    //
    // Initialization of 'Generator'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Fre:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "Fre: 1kHz");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
	  /*Gragh初始化*/
		hItem=WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
		GRAPH_SetBorder(hItem, 0, 0, 0, 0);
		hData_2=GRAPH_DATA_YT_Create(GUI_RED, 400, 0, 0);
		GRAPH_AttachData(hItem, hData_2);
		for(i=0;i<400;i++)
			GRAPH_DATA_YT_AddValue(hData_2,(I16)(Array_Wavedata[i]*1.0*130/1241+4));
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Fre+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        WaveFre_ADD();
//			  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//				memset(Disp_2,0,20);
//				sprintf(Disp_2,"Fre:%.1lfkHz",Fre_Wave*1.0/1000);
//				TEXT_SetText(hItem,Disp_2);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Fre-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        WaveFre_SUB();
//			  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//				memset(Disp_2,0,20);
//				sprintf(Disp_2,"Fre:%.1lfkHz",Fre_Wave*1.0/1000);
//				TEXT_SetText(hItem,Disp_2);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Sine'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				Change_Wave(SineWave);       //切换成正弦波
				for(i=0;i<400;i++)
				{
					GRAPH_DATA_YT_AddValue(hData_2,(I16)(Array_Wavedata[i]*1.0*130/1241+4));
				}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Sawtooth'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				Change_Wave(SawToothWave);       //切换成锯齿波
				for(i=0;i<400;i++)
				{
					GRAPH_DATA_YT_AddValue(hData_2,(I16)(Array_Wavedata[i]*1.0*130/1241+4));
				}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Square'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				Change_Wave(SquareWave);       //切换成方波
			  for(i=0;i<400;i++)
				{
					GRAPH_DATA_YT_AddValue(hData_2,(I16)(Array_Wavedata[i]*1.0*130/1241+4));
				}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Triangular'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				Change_Wave(TriWave);       //切换成三角波
			  for(i=0;i<400;i++)
				{
					GRAPH_DATA_YT_AddValue(hData_2,(I16)(Array_Wavedata[i]*1.0*130/1241+4));
				}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'ESC' 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				WM_DeleteTimer(hTimer_3);
        GUI_EndDialog(pMsg->hWin, 0);
				CreateMian();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
	case WM_TIMER:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				memset(Disp_2,0,20);
				sprintf(Disp_2,"Fre:%.1lfkHz",Fre_Wave*1.0/1000);
				TEXT_SetText(hItem,Disp_2);
				WM_RestartTimer(hTimer_3, 100);
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateGenerator
*/
WM_HWIN CreateGenerator(void);
WM_HWIN CreateGenerator(void) {
  WM_HWIN hWin;
//	Wave_Init(Fre_Wave,SineWave);  //输出波形初始话
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hTimer_3 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
