/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "pwm.h"
#include "string.h"
#include "stdlib.h"
#include "stdio.h"
#include "w25qxx.h"
#include "PWMDLG.h"
#include "MainDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x05)
#define ID_BUTTON_0     (GUI_ID_USER + 0x06)
#define ID_BUTTON_1     (GUI_ID_USER + 0x07)
#define ID_BUTTON_2     (GUI_ID_USER + 0x08)
#define ID_BUTTON_3     (GUI_ID_USER + 0x09)
#define ID_BUTTON_4     (GUI_ID_USER + 0x0A)
#define ID_BUTTON_5     (GUI_ID_USER + 0x0B)
#define ID_BUTTON_6     (GUI_ID_USER + 0x0C)
#define ID_BUTTON_7     (GUI_ID_USER + 0x0D)
#define ID_BUTTON_8     (GUI_ID_USER + 0x0E)
#define ID_BUTTON_9     (GUI_ID_USER + 0x0F)
#define ID_BUTTON_10     (GUI_ID_USER + 0x10)
#define ID_BUTTON_11     (GUI_ID_USER + 0x11)
#define ID_BUTTON_12     (GUI_ID_USER + 0x12)
#define ID_TEXT_0     (GUI_ID_USER + 0x13)
#define ID_EDIT_0     (GUI_ID_USER + 0x14)
#define ID_BUTTON_13     (GUI_ID_USER + 0x15)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static char get_num[50]={""};    //获取的数值
u16 num_len;   //数值长度
int temp_num=0;   //临时数据存放
u32 FLASH_SIZE=16*1024*1024;	//FLASH 大小为16字节
WM_HWIN hItem1;

//删除输入的数字
void delete_num()
{
	int     i = 0;
	EDIT_GetText(hItem1, get_num, 21);
	while (get_num[i] != '\0')
	{
		i++;
	}
	if (i <= 0)
	{
		i = 0;
		return;
	}
	get_num[i-1] = '\0';
	
	EDIT_SetText(hItem1, get_num);
}


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "PWM", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_0, 66, 121, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_1, 161, 121, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_2, 256, 121, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_3, 66, 196, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_4, 161, 197, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_5, 256, 197, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_6, 66, 273, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_7, 161, 273, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_8, 256, 273, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DEL", ID_BUTTON_9, 66, 349, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_10, 161, 349, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "STORE", ID_BUTTON_11, 256, 349, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OUTPUT", ID_BUTTON_12, 410, 237, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PWM:", ID_TEXT_0, 124, 74, 44, 21, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 170, 73, 80, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_13, 730, 0, 60, 30, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	hItem1 = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);  //设置背景色
		GUI_Clear();
	  break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'PWM'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'PWM:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_EnableBlink(hItem, 500, 1);
    EDIT_SetFont(hItem, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        strcat(get_num,"1");   //把1拼接到字符串后面
				temp_num=atoi(get_num);  //转化为数字
				EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        strcat(get_num,"2");   //把2拼接到字符串后面
				temp_num=atoi(get_num);  //转化为数字
				EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"3");   //把3拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"4");   //把4拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"5");   //把5拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"6");   //把6拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"7");   //把7拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"8");   //把8拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"9");   //把9拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'DEL'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        delete_num();  //删除一个数字
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
					strcat(get_num,"0");   //把0拼接到字符串后面
					temp_num=atoi(get_num);  //转化为数字
					EDIT_SetText(hItem1,get_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'STORE'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				num_len=strlen(get_num);
        W25QXX_Write((u8*)get_num,FLASH_SIZE-10,num_len);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'OUTPUT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				temp_num=atoi(get_num);  //转化为数字
				TIM_SetCompare1(TIM14,temp_num);
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by 'ESC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        TIM_Cmd(TIM14,DISABLE);
				GUI_EndDialog(pMsg->hWin, 0);
				CreateMian();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePWM
*/

WM_HWIN CreatePWM(void) {
  WM_HWIN hWin;
	TIM14_PWM_Init(10-1,84-1);
	W25QXX_Init();
	W25QXX_Read((u8*)get_num,FLASH_SIZE-10,num_len);
	temp_num=atoi(get_num);  //转化为数字
	TIM_SetCompare1(TIM14,temp_num);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
