/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WELCOMEDLG.h"
#include "MainDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x02)
#define ID_BUTTON_1  (GUI_ID_USER + 0x03)
#define ID_BUTTON_2  (GUI_ID_USER + 0x05)
#define ID_BUTTON_3  (GUI_ID_USER + 0x06)
#define ID_BUTTON_4  (GUI_ID_USER + 0x07)
#define ID_BUTTON_5  (GUI_ID_USER + 0x08)
#define ID_BUTTON_6  (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

u8 RO_dir=1;  //滚动方向
u8 speed=5;
WM_HTIMER hTimer_1;

/*矩形起始坐标*/
u16 x=0;  
u16 y=150;
u16 len_x,len_y;

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "WELCOME", ID_FRAMEWIN_0, 0, 300, 800, 180, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "RIGHT", ID_BUTTON_0, 204, 70, 60, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "UP", ID_BUTTON_1, 136, 31, 60, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LEFT", ID_BUTTON_2, 68, 70, 60, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DOWN", ID_BUTTON_3, 136, 108, 60, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Speed+", ID_BUTTON_4, 416, 57, 70, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Speed-", ID_BUTTON_5, 416, 110, 70, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ESC", ID_BUTTON_6, 730, 1, 60, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	case WM_PAINT:
			GUI_SetBkColor(GUI_WHITE);  //设置背景色
			GUI_Clear();
			break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'welcome'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'RIGHT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        RO_dir = str_ROR;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'UP'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        RO_dir = str_ROU;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'LEFT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				RO_dir = str_ROL;
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'DOWN'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        RO_dir = str_ROD;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Speed+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        speed+=2;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Speed-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				speed-=2;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'ESC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
//				GUI_SetBkColor(GUI_BLACK);		//设置背景颜色
//	      GUI_ClearRect(0,0,800,300-1);
        WM_DeleteTimer(hTimer_1);
				GUI_EndDialog(pMsg->hWin, 0);
				CreateMian();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
	case WM_TIMER:
		GUI_ClearRect(len_x,len_y,len_x+200,len_y+16);
	  len_x=x;
	  len_y=y;
		switch(RO_dir)
		{
			case str_ROL:
				GUI_DispStringAt("Welcome to Hduwireless",x,y);
				x-=speed;
			  break;
			case str_ROR:
				GUI_DispStringAt("Welcome to Hduwireless",x,y);
				x+=speed;
			  break;
			case str_ROU:
				GUI_DispStringAt("Welcome to Hduwireless",x,y);
				y-=speed;
			  break;
			case str_ROD:
				GUI_DispStringAt("Welcome to Hduwireless",x,y);
				y+=speed;
			  break;
		}
		if(x>=800 && x<1000)	x=0;
		else if(x<=0 || x>1000) x=800;
		else if (y>=300 && y<1000) y=0;
		else if (y<=0 || y>=1000) y=300;
		WM_RestartTimer(hTimer_1, 100);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createwelcome
*/

WM_HWIN CreateWELCOME(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  hTimer_1 = WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0);
	GUI_Delay(100);
	GUI_SetBkColor(GUI_BLACK);		//设置背景颜色
	GUI_ClearRect(0,0,800,300-1);
	GUI_SetColor(GUI_WHITE);       //设置前景色(如文本，画线等颜色)
	GUI_SetFont(GUI_FONT_16B_1);
//	GUI_DispStringAt("Welcome to Hduwireless",x,y);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/

